### ISSUE TITLE
This compatible with original goldsrc ??

### ISSUE THREAD

**Issue by Karaulov** [x6herbius/afterburner-compiletools#1]
@x6herbius this project compatible with original goldsrc (like cs 1.6/hl 1 ) ??

**Comment by x6herbius** [comment]
I'm not attempting to keep this compatible with the GoldSrc BSP spec (insofar as there is one), because the changes I'm making to the compilation code are specifically for Nightfire-related resources. The maps produced by these tools don't at the moment do anything more special than standard GoldSrc maps, so the original compile tools are your best bet for HL/CS/etc.
